# Generated by Django 3.0.4 on 2020-03-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20200312_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalskills',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='techskills',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
