# Generated by Django 3.0.4 on 2020-03-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_contactme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight', models.TextField(max_length=100)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='contactme',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
