# Generated by Django 3.0.4 on 2020-03-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20200312_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdescriptions',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
