# Generated by Django 3.0.4 on 2020-03-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20200324_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdescriptions',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
