# Generated by Django 3.0.4 on 2020-03-31 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_projectexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectexperience',
            name='end_month',
            field=models.CharField(choices=[('JAN', 'JAN'), ('FEB', 'FEB'), ('MAR', 'MAR'), ('APR', 'APR'), ('MAY', 'MAY'), ('JUN', 'JUN'), ('JUL', 'JUL'), ('AUG', 'AUG'), ('SEP', 'SEP'), ('OCT', 'OCT'), ('NOV', 'NOV'), ('DEC', 'DEC')], default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='projectexperience',
            name='end_year',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
